[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "json5>=0.12.0",
    "numpy>=2.3.1",
    "openai>=1.90.0",
    "pandas>=2.3.0",
    "python-dotenv>=1.1.0",
    "streamlit>=1.46.0",
]
