namespace Linedata.Mfact.Shared.Domain.MfactModels
{
    public class Fndmas
    {
       
            public string Fund { get; set; }                     
            public string? Acnam1 { get; set; }                    
            public string? Acnam2 { get; set; }                    
            public string? Officer1 { get; set; }                   
            public string? Officer2 { get; set; }                   
            public string? Officer3 { get; set; }                   
            public string? Add1 { get; set; }                       
            public string? Add2 { get; set; }                       
            public string? City { get; set; }                       
            public string? State { get; set; }                     
            public string? Zip { get; set; }                       
            public string? Country { get; set; }                   
            public string? Phone { get; set; }                     
            public DateTime? Start_Date { get; set; }             
            public string? Custac { get; set; }                     
            public string? Secrpt { get; set; }                     
            public string? Invdis { get; set; }                     
            public string? Glflag { get; set; }                     
            public string? Votauth { get; set; }                    
            public string? Secmgr { get; set; }                     
            public decimal? Gl_Batch { get; set; }                  
            public string? AcType { get; set; }                     
            public decimal? Variance1 { get; set; }                
            public decimal? Variance2 { get; set; }                
            public decimal? Variance3 { get; set; }                
            public decimal? Variance4 { get; set; }                
            public decimal? Variance5 { get; set; }                
            public decimal? Variance6 { get; set; }                
            public decimal? Variance7 { get; set; }                
            public decimal? Variance8 { get; set; }                
            public decimal? Variance9 { get; set; }                
            public decimal? Variance0 { get; set; }                
            public string? Domicile { get; set; }                   
            public decimal? SetPend { get; set; }                  
            public string? TaxYr { get; set; }                      
            public string? Comments { get; set; }                   
            public decimal? ValPend { get; set; }                  
            public string? Entity { get; set; }                     
            public string? LetFlg { get; set; }                     
            public string? TaxLot_Liq { get; set; }                  
            public string? Amort { get; set; }                       
            public decimal? Par_Value { get; set; }                 
            public string? D60_Price { get; set; }                  
            public string? MktPrem { get; set; }                   
            public string? MktDisc { get; set; }                   
            public string? AcqDisc { get; set; }                   
            public string? Oid_Method { get; set; }                  
            public DateTime? Mark_Date { get; set; }               
            public string? Mark_IdNo { get; set; }                   
            public string? Unsettle { get; set; }                   
            public string? Daily_Div { get; set; }                   
            public decimal? Fesl { get; set; }                      
            public string? Muller_Id { get; set; }                   
            public DateTime? Entry_Date { get; set; }              
            public decimal? Long_Value { get; set; }                 
            public decimal? Short_Val { get; set; }                 
            public string? Multi_Curr { get; set; }                  
            public string? Base_Curr { get; set; }                   
            public decimal? Bas_M_Decs { get; set; }                 
            public decimal? Bas_Q_Decs { get; set; }                 
            public string? Cur_Lotliq { get; set; }                  
            public string? Accru_Tax { get; set; }                   
            public decimal? ShareTypes { get; set; }                
            public string? Kenny_Id { get; set; }                    
            public string? Exp_Comp { get; set; }                     
            public string? Rev_Comp { get; set; }                     
            public string? Cap_Comp { get; set; }                     
            public string? Pric_Amort { get; set; }                  
            public string? Setl_Lcl { get; set; }                    
            public string? Auto_Trade { get; set; }                   
            public string? Hedge_Trad { get; set; }                   
            public string? Forwrd_Cat { get; set; }                   
            public string? Ff_Lot_Liq { get; set; }                   
            public string? Tbhist { get; set; }                      
            public string? DtcId { get; set; }                       
            public string? New_FwdTkr { get; set; }                  
            public string? Subunit { get; set; }                     
            public string? ComonPrice { get; set; }                  
            public string? Common_Fx { get; set; }                    
            public string? FundStatOn { get; set; }                  
            public string? Ntrpolated { get; set; }                  
            public string? R_Code1 { get; set; }                      
            public string? R_Code2 { get; set; }                      
            public string? R_Code3 { get; set; }                      
            public string? R_Code4 { get; set; }                      
            public string? R_Code5 { get; set; }                      
            public string? R_Code6 { get; set; }                      
            public string? R_Code7 { get; set; }                      
            public string? R_Code8 { get; set; }                      
            public string? R_Code9 { get; set; }                      
            public string? R_Code10 { get; set; }                     
            public string? R_Code11 { get; set; }                     
            public string? R_Code12 { get; set; }                     
            public string? R_Code13 { get; set; }                     
            public string? R_Code14 { get; set; }                     
            public string? R_Code15 { get; set; }                     
            public string? R_Code16 { get; set; }                     
            public string? R_Code17 { get; set; }                     
            public string? R_Code18 { get; set; }                     
            public string? R_Code19 { get; set; }                     
            public string? R_Code20 { get; set; }                     
            public decimal? R_Percnt1 { get; set; }                  
            public decimal? R_Percnt2 { get; set; }                  
            public decimal? R_Percnt3 { get; set; }                  
            public decimal? R_Percnt4 { get; set; }                  
            public decimal? R_Percnt5 { get; set; }                  
            public decimal? R_Percnt6 { get; set; }                  
            public decimal? R_Percnt7 { get; set; }                  
            public decimal? R_Percnt8 { get; set; }                  
            public decimal? R_Percnt9 { get; set; }                  
            public decimal? R_Percnt10 { get; set; }                 
            public decimal? R_Percnt11 { get; set; }                 
            public decimal? R_Percnt12 { get; set; }                 
            public decimal? R_Percnt13 { get; set; }                 
            public decimal? R_Percnt14 { get; set; }                 
            public decimal? R_Percnt15 { get; set; }                 
            public decimal? R_Percnt16 { get; set; }                 
            public decimal? R_Percnt17 { get; set; }                 
            public decimal? R_Percnt18 { get; set; }                 
            public decimal? R_Percnt19 { get; set; }                 
            public decimal? R_Percnt20 { get; set; }                 
            public string? R_Baseon1 { get; set; }                    
            public string? R_Baseon2 { get; set; }                    
            public string? R_Baseon3 { get; set; }                    
            public string? R_Baseon4 { get; set; }                    
            public string? R_Baseon5 { get; set; }                    
            public string? R_Baseon6 { get; set; }                    
            public string? R_Baseon7 { get; set; }                    
            public string? R_Baseon8 { get; set; }                    
            public string? R_Baseon9 { get; set; }                    
            public string? R_Baseon10 { get; set; }                   
            public string? R_Baseon11 { get; set; }                   
            public string? R_Baseon12 { get; set; }                   
            public string? R_Baseon13 { get; set; }                   
            public string? R_Baseon14 { get; set; }                   
            public string? R_Baseon15 { get; set; }                   
            public string? R_Baseon16 { get; set; }                   
            public string? R_Baseon17 { get; set; }                   
            public string? R_Baseon18 { get; set; }                   
            public string? R_Baseon19 { get; set; }                   
            public string? R_Baseon20 { get; set; }                   
            public string? Nasdaq_Tkr { get; set; }                   
            public DateTime? User_Date1 { get; set; }               
            public DateTime? User_Date2 { get; set; }               
            public DateTime? User_Date3 { get; set; }               
            public decimal? User_Num1 { get; set; }                  
            public decimal? User_Num2 { get; set; }                  
            public decimal? User_Num3 { get; set; }                  
            public string? User_Char1 { get; set; }                   
            public string? User_Char2 { get; set; }                   
            public string? User_Char3 { get; set; }                   
            public string? Yes_No1 { get; set; }                       
            public string? Yes_No2 { get; set; }                       
            public string? Yes_No3 { get; set; }                       
            public string? Yes_No4 { get; set; }                       
            public string? Yes_No5 { get; set; }                       
            public string? Amort2 { get; set; }                      
            public string? Amort3 { get; set; }                      
            public string? Smooth { get; set; }                       
            public string? Yes_No9 { get; set; }                       
            public string? Yes_No0 { get; set; }                       
            public string? Series { get; set; }                       
            public decimal? Legal { get; set; }                     
            public decimal? InvStruc { get; set; }                  
            public decimal? InvStrat { get; set; }                  
            public string? HedgeTek { get; set; }                     
            public string? Sponsor { get; set; }                      
            public DateTime? HedgeDate { get; set; }               
            public DateTime? CapDate { get; set; }                 
            public string? LhedgeNo { get; set; }                    
            public string? Inactive { get; set; }                     
            public string? Family { get; set; }                       
            public decimal? Nav_Decs { get; set; }                  
            public decimal? Unav_Decs { get; set; }                 
            public string? Nav_Rndg { get; set; }                      
            public decimal? Pop_Decs { get; set; }                  
            public string? Pop_Rndg { get; set; }                      
            public decimal? Share_Decs { get; set; }                
            public string? Unused { get; set; }                       
            public string? WebPortal { get; set; }                    
            public string? Pday { get; set; }                         
            public decimal? Ptime { get; set; }                     
            public string? Cmpcrf { get; set; }                       
            public string? Subhedge { get; set; }                     
            public string? Cfdcls { get; set; }                       
            public string? Cfddaily { get; set; }                     
            public string? Mrgcls { get; set; }                       
            public string? Mrgdaily { get; set; }                     
            public string? Netfwd { get; set; }                       
            public string? Mcsc { get; set; }                         
            public string? Indic { get; set; }                        
            public string? Longview { get; set; }                     
            public string? Shrgrp { get; set; }                       
            public string? Sbclass { get; set; }                      
            public string? Tccom { get; set; }                        
            public string? Tctrf { get; set; }                        
            public string? Comtrx { get; set; }                       
            public string? Trftrx { get; set; }                       
            public string? Mkrchr { get; set; }                       
            public string? Dash { get; set; }                         
            public string? Reval { get; set; }                        
            public decimal? Prem_Days { get; set; }                  
            public decimal? Mdisc_Days { get; set; }                 
            public decimal? Adisc_Days { get; set; }                 
            public decimal? Oid_Days { get; set; }                   
            public string? Cusip { get; set; }                        
            public decimal? Futsdd { get; set; }                     
            public decimal? Cfdsdd { get; set; }                     
            public string? Amt_Method { get; set; }                    
            public string? Fairval { get; set; }                      
            public string? Con_Lim { get; set; }                       
            public decimal? Con_Lvl { get; set; }                     
            public string? Ldc { get; set; }                          
            public string? Prc_Fnd { get; set; }                       
            public string? Rbp_Fnd { get; set; }                       
            public string? Fv_Fnd { get; set; }                        
            public string? Np_Fnd { get; set; }                        
            public string? Pcrf_Fnd { get; set; }                      
            public string? Wsh_Acno { get; set; }                     
            public string? Fx_Fnd { get; set; }                        
            public string? Id1 { get; set; }                          
            public string? FullAcc { get; set; }                      
            public string? CoupSmooth { get; set; }                   
            public string? Ntrpol { get; set; }                       
            public string? NavToAe { get; set; }                      
            public string? DistToAe { get; set; }                     
            public string? Lei { get; set; }                           
            public string? AllocNav { get; set; }                     
            public string? Ex_Naked { get; set; }                      
            public string? Col_Shrt { get; set; }                      
            public string? Supervisor { get; set; }                    
            public string? Team_Lead { get; set; }                     
            public string? Accountant { get; set; }                   
            public string? Admin_Contry { get; set; }                  
            public string? Del_Lead { get; set; }                       
            public string? Amtval { get; set; }                       
            public string? Uni_Desc { get; set; }                      
            public string? Futvmc { get; set; }                        
            public string? Cfdvmc { get; set; }                        
            public string? Mth_Prcs { get; set; }                      
            public string? Move_Vd { get; set; }                       
            public string? Slei { get; set; }                          
            public string? ValAmrt { get; set; }                      
            public DateTime? Rule_Start { get; set; }                
            public string? Ctry_Lot { get; set; }                      
            public string? Auto_CgDist { get; set; }                   
            public string? Auto_IncDist { get; set; }                  
            public string? Findex { get; set; }                        
            public string? Val_Time { get; set; }                       
            public string? InKind { get; set; }                        
            public decimal? Hash { get; set; }                        
        
    }
}