using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Linedata.Mfact.Shared.Domain.MfactModels
{
    public class SecrtyMkr
    {
        public string tkr { get; set; }
        public string? cusip { get; set; }
        public string? sedol { get; set; }
        public string? isin { get; set; }
        public string? ric { get; set; }
        public string? custom_id1 { get; set; }
        public string? custom_id2 { get; set; }
        public string? tkr_type { get; set; }
        public string? seccat { get; set; }
        public string? tkr_desc { get; set; }
        public string? desc2 { get; set; }
        public string? exch { get; set; }
        public DateTime? lsttrx { get; set; }
        public decimal? lstdiv { get; set; }
        public string? secgrp { get; set; }
        public string? report_13g { get; set; }
        public string? optionable { get; set; }
        public decimal? factor { get; set; }
        public string? glxcat { get; set; }
        public string? issuer { get; set; }
        public string? guarantor { get; set; }
        public string? state { get; set; }
        public string? country { get; set; }
        public string? currency { get; set; }
        public string? accrue { get; set; }
        public string? credit { get; set; }
        public string? no_price { get; set; }
        public string? no_dtc { get; set; }
        public string? rpt13f { get; set; }
        public string? divtst { get; set; }
        public string? inctst { get; set; }
        public decimal? estdiv { get; set; }
        public decimal? beta { get; set; }
        public decimal? outshs { get; set; }
        public DateTime? nxtacc { get; set; }
        public DateTime? expdat { get; set; }
        public string? undtkr { get; set; }
        public decimal? strike { get; set; }
        public decimal? conv_ratio { get; set; }
        public string? taxint { get; set; }
        public string? sap_rating { get; set; }
        public string? moodys { get; set; }
        public DateTime? matdat { get; set; }
        public int? int_cycle { get; set; }
        public DateTime? datdat { get; set; }
        public string? accmth { get; set; }
        public string? pool { get; set; }
        public string? mbs_type { get; set; }
        public decimal? mkt61 { get; set; }
        public DateTime? issue_date { get; set; }
        public decimal? issueprice { get; set; }
        public string? priceamort { get; set; }
        public string? mkt_prem { get; set; }
        public string? mkt_disc { get; set; }
        public string? acq_disc { get; set; }
        public string? oid_method { get; set; }
        public decimal? ytm_issue { get; set; }
        public decimal? exdiv_days { get; set; }
        public string? accinc_net { get; set; }
        public string? with_tax { get; set; }
        public decimal? face_value { get; set; }
        public int? lcl_m_decs { get; set; }
        public int? lcl_q_decs { get; set; }
        public int? lcl_p_decs { get; set; }
        public int? rate_cycle { get; set; }
        public DateTime? nxtratdate { get; set; }
        public int? dmnd_delay { get; set; }
        public string? taxcod { get; set; }
        public decimal? ytm { get; set; }
        public string? ntrpolated { get; set; }
        public string? inactive { get; set; }
        public string? which_aux { get; set; }
        public DateTime? euro_date { get; set; }
        public string? amt_flag { get; set; }
        public string? r_code1 { get; set; }
        public string? r_code2 { get; set; }
        public string? r_code3 { get; set; }
        public string? r_code4 { get; set; }
        public string? r_code5 { get; set; }
        public string? r_code6 { get; set; }
        public string? r_code7 { get; set; }
        public string? r_code8 { get; set; }
        public string? r_code9 { get; set; }
        public string? r_code10 { get; set; }
        public string? r_code11 { get; set; }
        public string? r_code12 { get; set; }
        public string? r_code13 { get; set; }
        public string? r_code14 { get; set; }
        public string? r_code15 { get; set; }
        public string? r_code16 { get; set; }
        public string? r_code17 { get; set; }
        public string? r_code18 { get; set; }
        public string? r_code19 { get; set; }
        public string? r_code20 { get; set; }
        public DateTime? user_date1 { get; set; }
        public DateTime? user_date2 { get; set; }
        public DateTime? user_date3 { get; set; }
        public decimal? user_num1 { get; set; }
        public decimal? user_num2 { get; set; }
        public decimal? user_num3 { get; set; }
        public string? user_char1 { get; set; }
        public string? user_char2 { get; set; }
        public string? user_char3 { get; set; }
        public string? yes_no1 { get; set; }
        public string? yes_no2 { get; set; }
        public string? yes_no3 { get; set; }
        public string? yes_no4 { get; set; }
        public string? yes_no5 { get; set; }
        public string? yes_no6 { get; set; }
        public string? yes_no7 { get; set; }
        public string? yes_no8 { get; set; }
        public string? yes_no9 { get; set; }
        public string? template { get; set; }
        public int? mbs_month { get; set; }
        public int? mbs_day { get; set; }
        public DateTime? date_added { get; set; }
        public string? hot_issue { get; set; }
        public string? cont_1256 { get; set; }
        public string? shrtterm { get; set; }
        public string? fedtax { get; set; }
        public string? statax { get; set; }
        public string? lcltax { get; set; }
        public string? findex { get; set; }
        public string? delset { get; set; }
        public string? polacc { get; set; }
        public DateTime? fpay { get; set; }
        public string? exch_noto { get; set; }
        public string? exch_notc { get; set; }
        public string? net_income { get; set; }
        public decimal? not_ino { get; set; }
        public decimal? not_inc { get; set; }
        public decimal? not_outo { get; set; }
        public decimal? not_outc { get; set; }
        public string? capprem { get; set; }
        public string? swpls { get; set; }
        public string? markit { get; set; }
        public string? markit_red { get; set; }
        public string? markit_oec { get; set; }
        public string? markittier { get; set; }
        public string? markit_pp { get; set; }
        public string? markit_frr { get; set; }
        public string? markit_fix { get; set; }
        public string? markit_flt { get; set; }
        public decimal? markit_fs { get; set; }
        public string? ib { get; set; }
        public string? und_index { get; set; }
        public decimal? bas_points { get; set; }
        public string? user_added { get; set; }
        public string? time_added { get; set; }
        public string? range { get; set; }
        public string? exdate { get; set; }
        public string? custom_id3 { get; set; }
        public string? tax_ls { get; set; }
        public int? prem_days { get; set; }
        public int? mdisc_days { get; set; }
        public int? adisc_days { get; set; }
        public int? oid_days { get; set; }
        public string? val_time { get; set; }
        public string? is_fund { get; set; }
        public string? prc_by_yld { get; set; }
        public string? Nrsro { get; set; }
        public string? Rating { get; set; }
        public int? Spread { get; set; }
        public int? Year { get; set; }
        public string? AccRat { get; set; }
        public string? TaxDat { get; set; }
        public string? BbgId { get; set; }
        public string? Rec { get; set; }
        public string? AccFix { get; set; }
        public string? Cmc { get; set; }
        public string? Rdc { get; set; }
        public int? RdcDay { get; set; }
        public string? Lei { get; set; }
        public int? Irreg_Freq { get; set; }
        public int? TPlus { get; set; }
        public string? Putt { get; set; }
        public int? Putt_Days { get; set; }
        public string? Compounded { get; set; }
        public string? intPayMeth { get; set; }
        public string? CompWeekends { get; set; }
        public string? SkipHoliday { get; set; }
        public int? SchdType { get; set; }
        public int? SchdParm1 { get; set; }
        public int? SchdParm2 { get; set; }
        public int? SchdParm3 { get; set; }
        public string? UniDesc { get; set; }
        public string? Tranche { get; set; }
        public string? Bnkdbt { get; set; }
        public string? AutMat_Off { get; set; }
        public string? Price_Id { get; set; }
        public string? InclMtrx { get; set; }
        public string? SetTrade { get; set; }
        public string? SetIncom { get; set; }
        public decimal? Hash { get; set; }
    }

}
