namespace Linedata.Mfact.Shared.Domain.MfactModels
{
    public class Glprm
    {
        public string fund { get; set; }
        public DateTime? ty_start { get; set; }
        public DateTime? ly_start { get; set; }
        public string? cash_acno { get; set; }
        public string? cap_shract { get; set; }
        public string? print_cat { get; set; }
        public string? print_grp { get; set; }
        public string? print_act { get; set; }
        public string? post_user { get; set; }
        public DateTime? postthruty { get; set; }
        public string? p_systimty { get; set; }
        public DateTime? cpstart_ty { get; set; }
        public string? trx_pst_ty { get; set; }
        public DateTime? p_sysdatty { get; set; }
        public string? inc_dr_act { get; set; }
        public string? inc_cr_act { get; set; }
        public DateTime? nav_date { get; set; }
        public DateTime? accfixdate { get; set; }
        public DateTime? accdivdate { get; set; }
        public DateTime? amtfixdate { get; set; }
        public DateTime? autpstdate { get; set; }
        public DateTime? propridate { get; set; }
        public DateTime? m2m_date { get; set; }
        public string? accfixuser { get; set; }
        public string? accdivuser { get; set; }
        public string? amtfixuser { get; set; }
        public string? autpstuser { get; set; }
        public string? propriuser { get; set; }
        public string? m2m_user { get; set; }
        public string? accfixtime { get; set; }
        public string? accdivtime { get; set; }
        public string? amtfixtime { get; set; }
        public string? autpsttime { get; set; }
        public string? propritime { get; set; }
        public string? m2m_time { get; set; }
        public DateTime? cpstart_ly { get; set; }
        public DateTime? postthruly { get; set; }
        public DateTime? p_sysdatly { get; set; }
        public string? p_systimly { get; set; }
        public string? p_user_ly { get; set; }
        public string? trx_pst_ly { get; set; }
        public string? trade_flag { get; set; }
        public string? captrxflag { get; set; }
        public string? exp_reimcr { get; set; }
        public string? exp_reimdr { get; set; }
        public string? weekend { get; set; }
        public string? initcapact { get; set; }
        public string? undist_inc { get; set; }
        public string? equalizton { get; set; }
        public string? setl_share { get; set; }
        public DateTime? eodincdate { get; set; }
        public string? eodincuser { get; set; }
        public string? eodinctime { get; set; }
        public DateTime? auttrxdate { get; set; }
        public string? auttrxuser { get; set; }
        public string? auttrxtime { get; set; }
        public string? nav_cycle { get; set; }
        public DateTime? split_date { get; set; }
        public DateTime? eoddivdate { get; set; }
        public string? eoddivtime { get; set; }
        public string? eoddivuser { get; set; }
        public DateTime? gnmpstdate { get; set; }
        public string? gnmpsttime { get; set; }
        public string? gnmpstuser { get; set; }
        public string? not_wt_cpy { get; set; }
        public string? not_fr_cpy { get; set; }
        public decimal? exp_amt1 { get; set; }
        public decimal? exp_amt2 { get; set; }
        public decimal? exp_rate1 { get; set; }
        public decimal? exp_rate2 { get; set; }
        public decimal? exp_rate3 { get; set; }
        public string? unused { get; set; }
        public string? split_user { get; set; }
        public string? split_time { get; set; }
        public string? m2m_dr_act { get; set; }
        public string? m2m_cr_act { get; set; }
        public string? fx_m2m_dr { get; set; }
        public string? fx_m2m_cr { get; set; }
        public string? acc_m2m_dr { get; set; }
        public string? acc_m2m_cr { get; set; }
        public string? pr_m2m_dr { get; set; }
        public string? pr_m2m_cr { get; set; }
        public string? wsh_acno { get; set; }
        public string? amtfixweekend { get; set; }
        public string? accfixweekend { get; set; }
        public string? accdivweekend { get; set; }
        public string? autpstweekend { get; set; }
        public string? eoddivweekend { get; set; }
        public string? gnmpstweekend { get; set; }
        public string? eodincweekend { get; set; }
        public string? auttrxweekend { get; set; }
        public string? m2mweekend { get; set; }
        public string? ntrrat_weekend { get; set; }
        public string? splitweekend { get; set; }
        public string? ubsfx_weekend { get; set; }
        public string? stcg_dr_act { get; set; }
        public string? ltcg_dr_act { get; set; }
        public string? roc_dr_act { get; set; }
        public string? stcg_cr_act { get; set; }
        public string? ltcg_cr_act { get; set; }
        public string? navtrx_ty { get; set; }
        public string? navtrx_ly { get; set; }
        public string? redfees { get; set; }
        public string? lospaid { get; set; }
        public DateTime? xchang_date { get; set; }
        public string? xchang_time { get; set; }
        public string? xchang_user { get; set; }
        public string? xchang_weekend { get; set; }
        public decimal? hash { get; set; }
    }

}